### ISSUE TITLE
poppler binaries are failing on cedar-14 stack

### ISSUE THREAD

**Issue by gsar** [BauCloud/heroku-buildpack-poppler#4]
Looks like cedar-14 doesn't provide liblcms.so.1 and libtiff.so.4.

  $ heroku run bash
  ~ $ pwd
  /app
  ~$ ./bin/pdfinfo -v
  ./bin/pdfinfo: error while loading shared libraries: liblcms.so.1: cannot open shared object file: No such file or directory
  ~$ ldd ./bin/pdfinfo
        linux-vdso.so.1 =>  (0x00007fff9878a000)
        libpoppler.so.34 => /app/vendor/poppler/lib/libpoppler.so.34 (0x00007fec6cfe6000)
        liblcms.so.1 => not found
        libtiff.so.4 => not found
        libjpeg.so.62 => /app/vendor/libjpeg-turbo/lib/libjpeg.so.62 (0x00007fec6cd5e000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fec6cb37000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fec6c8fb000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fec6c658000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fec6c42d000)
        libz.so.1 => /app/vendor/zlib/lib/libz.so.1 (0x00007fec6c216000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fec6bf12000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fec6bc0b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec6b845000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fec6b62f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec6b410000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fec6d516000)
        liblcms.so.1 => not found
        libtiff.so.4 => not found

Note last two lines.  Heroku seems to have upgraded to liblcms 2.x and libtiff 5.x:

  ~ $ ls -l /usr/lib/x86_64-linux-gnu/liblcms*
  lrwxrwxrwx 1 root root     17 Jan 16  2014 /usr/lib/x86_64-linux-gnu/liblcms2.so -> liblcms2.so.2.0.5
  lrwxrwxrwx 1 root root     17 Jan 16  2014 /usr/lib/x86_64-linux-gnu/liblcms2.so.2 -> liblcms2.so.2.0.5
  -rw-r--r-- 1 root root 346928 Jan 16  2014 /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.5
  ~ $ ls -l /usr/lib/x86_64-linux-gnu/libtiff*
  -rw-r--r-- 1 root root 733918 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiff.a
  -rw-r--r-- 1 root root    952 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiff.la
  lrwxrwxrwx 1 root root     16 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiff.so -> libtiff.so.5.2.0
  lrwxrwxrwx 1 root root     16 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiff.so.5 -> libtiff.so.5.2.0
  -rw-r--r-- 1 root root 467208 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.0
  -rw-r--r-- 1 root root   8462 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiffxx.a
  -rw-r--r-- 1 root root    966 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiffxx.la
  lrwxrwxrwx 1 root root     18 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiffxx.so -> libtiffxx.so.5.2.0
  lrwxrwxrwx 1 root root     18 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiffxx.so.5 -> libtiffxx.so.5.2.0
  -rw-r--r-- 1 root root  10160 May  5  2014 /usr/lib/x86_64-linux-gnu/libtiffxx.so.5.2.0

**Comment by ssaunier** [comment]
Hi guys, did you manage to create a buildpack which works on cedar-14, or do you have amazon-hosted packages that you could share with the community if you use the heroku-buildpack-vendorbinaries approach?

Thank you!

**Comment by tmaier** [comment]
Hi,

i just marked the buildpack as deprecated. 

b73f8c44cae777902185a57ba1564a02af3fc408 mentions also a solution.
